[MeasureAudio1]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=1

[MeterBar1]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio1

[MeasureAudio2]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=2

[MeterBar2]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio2

[MeasureAudio3]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=3

[MeterBar3]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio3

[MeasureAudio4]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=4

[MeterBar4]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio4

[MeasureAudio5]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=5

[MeterBar5]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio5

[MeasureAudio6]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=6

[MeterBar6]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio6

[MeasureAudio7]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=7

[MeterBar7]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio7

[MeasureAudio8]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=8

[MeterBar8]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio8

[MeasureAudio9]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=9

[MeterBar9]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio9

[MeasureAudio10]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=10

[MeterBar10]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio10

[MeasureAudio11]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=11

[MeterBar11]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio11

[MeasureAudio12]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=12

[MeterBar12]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio12

[MeasureAudio13]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=13

[MeterBar13]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio13

[MeasureAudio14]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=14

[MeterBar14]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio14

[MeasureAudio15]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=15

[MeterBar15]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio15

[MeasureAudio16]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=16

[MeterBar16]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio16

[MeasureAudio17]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=17

[MeterBar17]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio17

[MeasureAudio18]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=18

[MeterBar18]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio18

[MeasureAudio19]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=19

[MeterBar19]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio19

[MeasureAudio20]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=20

[MeterBar20]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio20

[MeasureAudio21]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=21

[MeterBar21]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio21

[MeasureAudio22]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=22

[MeterBar22]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio22

[MeasureAudio23]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=23

[MeterBar23]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio23

[MeasureAudio24]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=24

[MeterBar24]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio24

[MeasureAudio25]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=25

[MeterBar25]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio25

[MeasureAudio26]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=26

[MeterBar26]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio26

[MeasureAudio27]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=27

[MeterBar27]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio27

[MeasureAudio28]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=28

[MeterBar28]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio28

[MeasureAudio29]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=29

[MeterBar29]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio29

[MeasureAudio30]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=30

[MeterBar30]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio30

[MeasureAudio31]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=31

[MeterBar31]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio31

[MeasureAudio32]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=32

[MeterBar32]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio32

[MeasureAudio33]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=33

[MeterBar33]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio33

[MeasureAudio34]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=34

[MeterBar34]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio34

[MeasureAudio35]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=35

[MeterBar35]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio35

[MeasureAudio36]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=36

[MeterBar36]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio36

[MeasureAudio37]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=37

[MeterBar37]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio37

[MeasureAudio38]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=38

[MeterBar38]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio38

[MeasureAudio39]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=39

[MeterBar39]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio39

[MeasureAudio40]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=40

[MeterBar40]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio40

[MeasureAudio41]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=41

[MeterBar41]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio41

[MeasureAudio42]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=42

[MeterBar42]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio42

[MeasureAudio43]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=43

[MeterBar43]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio43

[MeasureAudio44]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=44

[MeterBar44]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio44

[MeasureAudio45]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=45

[MeterBar45]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio45

[MeasureAudio46]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=46

[MeterBar46]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio46

[MeasureAudio47]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=47

[MeterBar47]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio47

[MeasureAudio48]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=48

[MeterBar48]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio48

[MeasureAudio49]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=49

[MeterBar49]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio49

[MeasureAudio50]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=50

[MeterBar50]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio50

[MeasureAudio51]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=51

[MeterBar51]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio51

[MeasureAudio52]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=52

[MeterBar52]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio52

[MeasureAudio53]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=53

[MeterBar53]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio53

[MeasureAudio54]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=54

[MeterBar54]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio54

[MeasureAudio55]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=55

[MeterBar55]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio55

[MeasureAudio56]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=56

[MeterBar56]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio56

[MeasureAudio57]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=57

[MeterBar57]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio57

[MeasureAudio58]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=58

[MeterBar58]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio58

[MeasureAudio59]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=59

[MeterBar59]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio59

[MeasureAudio60]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=60

[MeterBar60]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio60

[MeasureAudio61]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=61

[MeterBar61]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio61

[MeasureAudio62]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=62

[MeterBar62]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio62

[MeasureAudio63]
Measure=Plugin
Plugin=AudioLevel
Parent=MeasureAudio
Type=Band
BandIdx=63

[MeterBar63]
Meter=Bar
Group=Bar
MeterStyle=MeterBar
MeasureName=MeasureAudio63